# frozen_string_literal: true

require_relative 'meta'
require_relative '../base'
require_relative 'step/charter_auction'

module Engine
  module Game
    module G18WE
      module Entities
        COMPANIES = [].freeze

        CORPORATIONS = [
          {
            sym: 'PLM',
            name: 'Paris à Lyon et à la Méditerranée',
            logo: '18WE/PLM',
            simple_logo: '18WE/PLM.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'G20',
            color: '#FFFF00',
            text_color: '#DD571C',
            reservation_color: nil,
          },
          {
            sym: 'SFR',
            name: 'Società Generale delle Strade Ferrate Romane',
            logo: '18WE/SFR',
            simple_logo: '18WE/SFR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'J21',
            color: '#0A1172',
            text_color: '#FFFFFF',
            reservation_color: nil,
          },
          {
            sym: 'PO',
            name: 'Chemin de Fer de Paris-Orléans',
            logo: '18WE/PO',
            simple_logo: '18WE/PO.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'E12',
            color: '#FFFF00',
            text_color: '#0492C2',
            reservation_color: nil,
          },
          {
            sym: 'DSJ',
            name: 'Det Sjællandske Jernbaneselskab',
            logo: '18WE/DSJ',
            simple_logo: '18WE/DSJ.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'K2',
            color: '#5DBB63',
            text_color: '#30430E',
            reservation_color: nil,
          },
          {
            sym: 'BHB',
            name: 'Berlin-Hamburger Bahn',
            logo: '18WE/EUR',
            simple_logo: '18WE/EUR.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'J5',
            color: '#FF3030',
            text_color: '#710193',
            reservation_color: nil,
          },
          {
            sym: 'SFAI',
            name: 'Società per le strade ferrate dell Alta Italia',
            logo: '18WE/SFAI',
            simple_logo: '18WE/SFAI.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'I18',
            color: '#FF6A06',
            text_color: '#C00000',
            reservation_color: nil,
          },
          {
            sym: 'SB',
            name: 'Südbahn',
            logo: '18WE/SB',
            simple_logo: '18WE/SB.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'L15',
            color: '#A0A0A0',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'HSM',
            name: 'Hollandsche IJzeren Spoorweg-Maatschappij',
            logo: '18WE/LD',
            simple_logo: '18WE/LD.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'H7',
            color: '#FF6A06',
            text_color: '#0A1172',
            reservation_color: nil,
          },
          {
            sym: 'MAV',
            name: 'Magyar Államvasutak',
            logo: '18WE/MAV',
            simple_logo: '18WE/MAV.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'O14',
            color: '#FFFF00',
            text_color: '#D00000',
            reservation_color: nil,
          },
          {
            sym: 'Nord',
            name: 'Chemin de Fer du Nord',
            logo: '18WE/Nord',
            simple_logo: '18WE/Nord.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'E10',
            color: '#A1CAF1',
            text_color: '#B00000',
            reservation_color: nil,
          },
          {
            sym: 'Midi',
            name: 'Chemin de Fer du Midi',
            logo: '18WE/Midi',
            simple_logo: '18WE/Midi.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'C16',
            color: '#C0C0C0',
            text_color: '#B64900',
            reservation_color: nil,
          },
          {
            sym: 'Est',
            name: 'Chemin de Fer de l Est',
            logo: '18WE/Est',
            simple_logo: '18WE/Est.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'B13',
            color: '#C0C0C0',
            text_color: '#355E3B',
            reservation_color: nil,
          },
          {
            sym: 'KFNB',
            name: 'Kaiser Ferdinands-Nordbahn',
            logo: '18WE/KFNB',
            simple_logo: '18WE/KFNB.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'L11',
            color: '#A1CAF1',
            text_color: '#082567',
            reservation_color: nil,
          },
          {
            sym: 'GC',
            name: 'Grand Central',
            logo: '18WE/GC',
            simple_logo: '18WE/GC.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'D19',
            color: '#ff0000',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'KSS',
            name: 'Königlich Sächsische Staatseisenbahnen',
            logo: '18WE/KSS',
            simple_logo: '18WE/KSS.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'L9',
            color: '#FFFF00',
            text_color: '#000000',
            reservation_color: nil,
          },
          {
            sym: 'WW',
            name: 'Warschau-Wiener Eisenbahn',
            logo: '18WE/WW',
            simple_logo: '18WE/WW.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'O10',
            color: '#D2B55B',
            text_color: '#355E3B',
            reservation_color: nil,
          },
          {
            sym: 'LV',
            name: 'Strada ferrata Ferdinandea Lombardo-Veneta',
            logo: '18WE/LV',
            simple_logo: '18WE/LV.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'K16',
            color: '#D2B55B',
            text_color: '#FF0000',
            reservation_color: nil,
          },
          {
            sym: 'Rhe',
            name: 'Rheinische Eisenbahn-Gesellschaft',
            logo: '18WE/Rhe',
            simple_logo: '18WE/Rhe.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'H11',
            color: '#C7EA46',
            text_color: '#0B6623',
            reservation_color: nil,
          },
          {
            sym: 'B',
            name: 'État Belge',
            logo: '18WE/B',
            simple_logo: '18WE/B.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'G8',
            color: '#FFC0C0',
            text_color: '#8B008B',
            reservation_color: nil,
          },
          {
            sym: 'Ouest',
            name: 'Chemin de Fer de l Ouest',
            logo: '18WE/Ouest',
            simple_logo: '18WE/Ouest.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'C12',
            color: '#FFFF00',
            text_color: '#8B008B',
            reservation_color: nil,
          },
          {
            sym: 'POB',
            name: 'Preußische Ostbahn',
            logo: '18WE/POB',
            simple_logo: '18WE/POB.alt',
            float_percent: 50,
            shares: [30, 10, 10, 10, 10, 10, 10, 10],
            max_ownership_percent: 100,
            tokens: [0, 0, 0],
            coordinates: 'N5',
            color: '#FFFF00',
            text_color: '#8B008B',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
